# Generated by Django 5.0.4 on 2024-05-06 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('On_time_delivery_rate', models.FloatField(default=0.0)),
                ('quality_rating_avg', models.FloatField(default=0.0)),
                ('fulfilment_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_details', models.BigIntegerField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='api.metrics')),
            ],
        ),
        migrations.AddField(
            model_name='metrics',
            name='Vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_data', to='api.vendor'),
        ),
    ]
