# Generated by Django 5.0.4 on 2024-05-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='api.metrics'),
        ),
    ]
