# Generated by Django 5.0.4 on 2024-05-07 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendor_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Purchase_Order_Tracking',
            fields=[
                ('po_number', models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'COMPLETED'), ('CN', 'CANCELLED'), ('P', 'PENDING')], max_length=12)),
                ('quality_rating', models.FloatField()),
                ('issue_date', models.DateField()),
                ('acknowledgment_date', models.DateField()),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendor')),
            ],
        ),
    ]
