# Generated by Django 5.0.4 on 2024-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vendor_contact_details_purchase_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='average_response_time',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_tracking',
            name='quality_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
